source 'https://rubygems.org'

gem 'awspec'
gem 'confidante', '>= 0.28.0'
gem 'git'
gem 'nokogiri'
gem 'rake'
gem 'rake_circle_ci', '>= 0.11.0'
gem 'rake_github', '>= 0.11.0'
gem 'rake_gpg', '>= 0.18.0'
gem 'rake_ssh', '>= 0.8.0'
gem 'rake_terraform', '>= 1.23.0'
gem 'rspec'
gem 'semantic'
