source 'https://rubygems.org'

gem 'awspec', '>= 1.26.0'
gem 'confidante'
gem 'git'
gem 'nokogiri'
gem 'rake'
gem 'rake_circle_ci'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_ssh'
gem 'rake_terraform'
gem 'rspec'
gem 'semantic'
