---
region: 'eu-west-2'

component: 'test'

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

acl: "private"

include_source_policy_json: "false"

mfa_delete: "false"
enable_access_logging: "no"

allow_destroy_when_objects_present: "no"

public_access_block:
  block_public_acls: "false"
  block_public_policy: "false"
  ignore_public_acls: "false"
  restrict_public_buckets: "false"