---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  bucket_name: "infrablocks-encrypted-%{hiera('deployment_identifier')}"

  acl: "%{hiera('acl')}"

  include_source_policy_json: "%{hiera('include_source_policy_json')}"

  mfa_delete: "%{hiera('mfa_delete')}"
  enable_access_logging: "%{hiera('enable_access_logging')}"

  allow_destroy_when_objects_present: "%{hiera('allow_destroy_when_objects_present')}"

  kms_key_arn: "%{hiera('kms_key_arn')}"

  public_access_block: "%{hiera('public_access_block')}"
